#pragma once

enum class ACTION_KEY
{
	SECONDHAND_LIST_VIEW,
	/*PARTTIME_LIST_VIEW,*/
	LIFEQUE_LIST_VIEW,
	/*HOBBY_LIST_VIEW,*/
	SECONDHAND_ARTICLE_VIEW,
	/*PARTTIME_ARTICLE_VIEW,*/
	LIFEQUE_ARTICLE_VIEW,
	/*HOBBY_ARTICLE_VIEW,*/

	SECONDHAND_LIST_DOMAIN = 100,
	/*PARTTIME_LIST_DOMAIN,*/
	LIFEQUE_LIST_DOMAIN,
	/*HOBBY_LIST_DOMAIN,*/
	SECONDHAND_ARTICLE_DOMAIN,
	/*PARTTIME_ARTICLE_DOMAIN,*/
	LIFEQUE_ARTICLE_DOMAIN,
	/*HOBBY_ARTICLE_DOMAIN,*/
};